"""Initial baseline

Revision ID: 0762ca80777a
Revises: 
Create Date: 2026-08-14 16:47:13.072704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0762ca80777a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'action',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('USER_REGISTER', 'USER_LOGIN', 'USER_LOGOUT', 'DATA_EXPORT', 'ACCOUNT_DELETE', 'PASSWORD_RESET_REQUEST', 'PASSWORD_RESET_COMPLETE', 'ADMIN_VIEW_USER', 'ADMIN_VIEW_SESSION', 'CONSENT_GIVEN', 'DUPLICATE_FLAGGED', 'DUPLICATE_REVIEWED', 'USER_PROFILE_UPDATE', 'SINGLE_USE_CREATED', 'SINGLE_USE_LOCKED', 'SINGLE_USE_ADMIN_UNLOCK', 'SINGLE_USE_DELETED', name='auditaction'),
               existing_nullable=False)
    
    #op.create_unique_constraint('uq_behavioural_type_code', 'behavioural_types', ['code'])
    op.alter_column('duplicate_flags', 'prior_registry_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    
    op.alter_column('questions', 'option_a_factor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('questions', 'option_b_factor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    
    op.alter_column('users', 'single_use_status',
               existing_type=mysql.ENUM('pending_registration', 'active', 'locked', 'admin_unlocked'),
               type_=sa.String(length=50),
               existing_nullable=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_single_use_deletion'), 'users', ['is_single_use', 'deletion_scheduled_at', 'deleted_at'], unique=False)
    op.alter_column('users', 'single_use_status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('pending_registration', 'active', 'locked', 'admin_unlocked'),
               existing_nullable=True)
    op.drop_index(op.f('ix_session_activity_logs_session_id'), table_name='session_activity_logs')
    op.drop_index(op.f('ix_session_activity_logs_created_at'), table_name='session_activity_logs')
    op.create_index(op.f('idx_sal_session'), 'session_activity_logs', ['session_id'], unique=False)
    op.create_index(op.f('idx_sal_created'), 'session_activity_logs', ['created_at'], unique=False)
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('3'), 'questions', 'behavioural_factors', ['option_a_factor_id'], ['id'])
    op.create_foreign_key(op.f('2'), 'questions', 'behavioural_types', ['behavioural_type_id'], ['id'])
    op.create_foreign_key(op.f('1'), 'questions', 'forms', ['form_id'], ['id'])
    op.create_foreign_key(op.f('4'), 'questions', 'behavioural_factors', ['option_b_factor_id'], ['id'])
    op.alter_column('questions', 'option_b_factor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('questions', 'option_a_factor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'duplicate_flags', type_='foreignkey')
    op.create_foreign_key(op.f('2'), 'duplicate_flags', 'applicant_registry', ['prior_registry_id'], ['id'])
    op.alter_column('duplicate_flags', 'prior_registry_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint('uq_behavioural_type_code', 'behavioural_types', type_='unique')
    op.create_index(op.f('uq_form_type_code'), 'behavioural_types', ['code'], unique=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.Enum('USER_REGISTER', 'USER_LOGIN', 'USER_LOGOUT', 'DATA_EXPORT', 'ACCOUNT_DELETE', 'PASSWORD_RESET_REQUEST', 'PASSWORD_RESET_COMPLETE', 'ADMIN_VIEW_USER', 'ADMIN_VIEW_SESSION', 'CONSENT_GIVEN', 'DUPLICATE_FLAGGED', 'DUPLICATE_REVIEWED', 'USER_PROFILE_UPDATE', 'SINGLE_USE_CREATED', 'SINGLE_USE_LOCKED', 'SINGLE_USE_ADMIN_UNLOCK', 'SINGLE_USE_DELETED', name='auditaction'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
